language: node_js
node_js:
- '8'
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: MlHWpeirvX5TOmA1wm3CPXzrkhDA/rRHDl55+4fGgqmIks/l542AHwEXRuBPjBeaOClpr6nuJmr8a4cnSFSZ9W9f9+7kMx8eLB1sWoNl20hTJ3LMfiB/ua3RHmCDZCsuhlYs1H1r7VrjZhtjkSkNRgmskXx2jOW8QtozuDGyIGka/HV0aPLbXKiwhEA16iyqD9kZc7ZQaSM2T4QQxcMW3tbr8PLfA0C6EYE75MV8u2BP6pRJ+rNtUnnmqwHeWOU4+Ytv+l78TyvXgAyxVr13HkcJnGErKQiNymlVptyia17cQje9fxyqgKYtZVqgDDQVLtIqyuYC7QN38a3MefiByA+JxzXfI8cTQMoFVs6oCoRXoONiwluUmerOl7WIKcP8gnLqbOXA+VIV3BqZA4JwKUsxZgHjF/fa26YuGn0kUmnc1lXRJCRd462Fy+ugReYAokfajMnXH3UedR7X5QT5vgLM9ev/GxLxuRohUV0F4ETbxi3Uw4YnP0/al153yNE0sYM9/HAfiJks73DfkUURjZPmriPYKjj2E90om1KICXWNkxsqWhGqo578YYh0eaQXrqol7VEyM8dgw9fCNbnYGIu7W5ifwzsQjTq4JF8iCt1bx1KGewnvNF+wCJKWFgd2AFWcWo7mbNljY+0pdacEJPiuj1jMWKL9wGqPRiut3Ew=
