language: node_js
node_js:
- '8'
script:
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: MzL4N4BgtxSVJ4lzyq6Qpd5SSAWQYpQzf6LUeUsHEpVfNHl6bex7W4AMTg6YMOqvutjeL96ZLUMQpEeAsuq7+/JZzEFabAeyySHDd8WfbN2wfTynDogebD7adB5+/uW5wlxhoo6rXOuEi4RJye8abML3jxta+dHevfbXn9Pb5X5lrN10FnKs0wokCfqTEtCiS1YtsJyVCdPLbOY/UwCcu3olLH5pUiB+4hgj5mmMA98V1VsPzk2yPuuLRV9W1OXxCzGDmoxSG9l7YYXLXrATJ+ggbBm8doiOJPZ4lbwtKZSMOP0jYcpdZgTNqcvLPhl5raNDRx0OZ9JxrMw4CB8LUjby7DJAxE2bD1awv6B+so68CCPjb7tvMl05KNcRsJPendE1t4iCdZUYN0LkdriwlqTzemqS54YYzPzEAo8VfsUOOz+x85itQO5xM7zrSjzjyIX+PHVPvGuvjKUlX99jTABpUBfCYKLPI0qfnCvV/dyaXOH2s3EcO5Cr+V4ql6GqxaQ5A1gzBMqoUAYUl8vYsQLOwkZFtFFup4lEGFLRtBhObxKSsWK8yKydkGjbuzKp3M9tr3jkC0g5f2fdbUN5I3zIIolRmtk3Vtcd+u/etRen4wIYdfXp5KHtXHYPCgM59FaltiPdzzbmCx3uriJd8eKvz998xyozokeL2ZhS1pI=
  app: graphql-api
  on:
    repo: ReactFinland/graphql-api
