language: node_js
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: BdkywhfZBRyJWgHMYi79e9cv8wvxMZFOKcWcXc/OE5ZdAQpZAEbh6ELV3RLBJk74YZIq1VrWqyNXBAyaOHHsXXjoul80uopu3N9FD5vDBzTHdgxToHJjDOdC1AkQjF8TBmOFMGLc45mo92yUyLU5OVITte7bI0ltD4Tsh6PpXJQpRX4HuNw05HpI9Dw1pNMfxzNq02/JaOaTb31fqJ1evkhKBKFqu8b3A2iv6l3qSzSh4vLtf1R97GrjVoEh/xsrX9aguJcy5cBGxY1h2BVeBlxp72CvfJxpqGwMxvcwmRLEX6FSNquzCMvF4DUGTMFIjMqeLKNUSGTRx1rHqYSNAwm14JIhcySp+ocim8Acsci8ucTER39+xuvX6d0Vmc8cb+fxRY8r05OHKjlvzFS7nczrkMlXwgz/voMrnja31jb8C5cQUhCRgJY+bNJfove3Q8/cYoQ9It8STfQkGVVcRjqE2luh2FdEA9vfCMrxzvau3rgbKIk9W4vBMEy6bqdmgEn63Q/tx1IhnAkGwYw8PUMguAYv2zaGXi2j+mShA63s03upOtKcvHhfT7408XqoeEUWVO1gMnmv1h13cj1i2pcTsONF0eneWaZ6xYOJggY6qxaNX+bhQAMO/a7sHhrkdzYndTqAgVOo/1+nlQGDXKz3X9yfHlYWWFaoslZwR84=
